apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-user-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pet-user-management
  template:
    metadata:
      labels:
        app: pet-user-management
    spec:
      containers:
        - name: api
          image: nicoberzunces/pet-user-management:latest
          ports:
            - containerPort: 18868
          env:
            - name: PORT
              value: "18868"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
